# baseurl = "./" # local only
baseurl = "https://rvo.lt/" #{{ .Site.BaseURL }} "/" && netlify
# relativeURLs = "true" #https://github.com/gohugoio/hugo/issues/985
languageCode = "en-us"
#languageCode = "en-gb" #Initial configuration reset
title = "RVO.LT" #FAIRtech Revolution | Rvo.lt

[Params]
  #author = "Alessandro Ronca" #https://duckduckgo.com/?q=%22config.toml%22+%22.author%22&t=osx
  description = "Change Artisans RVO.LT" #Artisans for Change, join the RVO.LT
  #description = "This isn't a paradigm shift: this is a RVO.LT" #Rvo.lt

  #[[Params.assignment]]
    #assignment = ""

  #[[Params.location]]
    #location = ""

## As of v0.20, all content files include a default "categories" value that's the same as the section. This was a cheap future-proofing method and should/could be changed accordingly.

[taxonomies]
  tag = "tags"
  area = "areas"
  level = "levels"
  category = "categories"
  #region = "regions"
  #price = "prices"

[Params.widgets]
  #search = true # Enable "Search" widget
  region = "regions"
  price = "prices"

  [[Params.social]]
    icon = "Email"
    site = "Email"
    url = "mailto:fairtech@pm.me"
    user = "fairtech@pm.me"

  [[Params.social]]
    icon = "Twitter"
    site = "Twitter"
    url = "https://twitter.com/fairtechrvolt"
    user = "@FairTechRvolt"

  [[Params.social]]
    icon = "partial 'social-icon' (dict 'link' '#' 'svg' 'icons-facebook')"
    site = "Facebook"
    # url = "https://it-it.facebook.com/risparmiaenergia/"
    url = "https://www.facebook.com/PeRIlParcodellaEnergiaRinnovabile/"

  [[Params.social]]
    icon = "youtube"
    site = "Youtube"
    url = "https://www.youtube.com/user/PeRParcodellEnergia/videos"
    #url = "https://www.youtube.com/user/risparmiaenergia/videos"

  [[Params.links]]
    title = "Email"
    url = "mailto:fairtech@pm.me"
